[package]
name = "sqlsmith-rs-server"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "server"
path = "main.rs"

[dependencies]
anyhow = "1.0.98"
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.29.0"
strum = { version = "0.27.1", features = ["derive"] }