[package]
name = "sqlsmith-rs-common"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
fern = "0.7.1"
humantime = "2.2.0"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sqlsmith-rs-drivers = { path = "../drivers" }
